spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}

dictionary:
  merriam-webster:
    api-key: ${MERRIAM_WEBSTER_API_KEY}

translation:
  azure:
    api-key: ${AZURE_TRANSLATOR_KEY}
    region: ${AZURE_TRANSLATOR_REGION}

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}

logging:
  structured:
    format:
      console: logstash
