-- V22: Deactivate onboarding reading v1 and insert onboarding reading v2

UPDATE onboarding_readings
SET active = FALSE
WHERE version = 1;

INSERT INTO onboarding_readings (title, content, active, version, created_at)
VALUES (
    'Finding a Voice in a New Harbor',
    'Elena moved to the coastal town in early autumn, carrying two suitcases and an ambitious desire to build a quiet life away from the rush of the capital. During her first week, ordinary tasks demanded surprising attention. Every morning, she woke up early to the sound of seagulls and walked along the cobblestone street toward the neighborhood market. In the beginning, simple interactions felt like minor achievements. Ordering bread at the bakery, asking for directions to the train station, and buying fresh vegetables required deliberate focus. The elderly baker always greeted her with a warm smile, speaking slowly so she could understand the local prices. Elena wrote down new words in a small notebook she kept in her jacket pocket. She recorded everyday terms for household items, food, weather, and daily transport. Her apartment was modest, with a wooden table placed near a large window that overlooked the harbor. Sitting there with a cup of hot tea after work, she reviewed her notes and listened to the distant rhythm of evening traffic. Although her routine was predictable, each day brought a quiet sense of purpose as familiar sights gradually replaced her initial disorientation.

By the second month, Elena felt ready to venture beyond her immediate neighborhood. She accepted a temporary position at a local community library, organizing shelves and helping visitors find historical archives. The work exposed her to a wider range of conversations and unexpected social situations. Colleagues shared anecdotes during lunch breaks, discussing local festivals, family traditions, and municipal projects. At first, Elena hesitated to participate actively, worried that her pronunciation would sound clumsy or that she might misunderstand a colloquial phrase. However, a friendly coworker named Marcus encouraged her to contribute. He explained that making mistakes was an unavoidable part of any authentic transition. Elena noticed that people appreciated genuine curiosity far more than grammatical perfection. She began attending weekly discussion circles at the community center, where residents gathered to debate books, travel experiences, and environmental initiatives. Engaging in these lively exchanges challenged her listening comprehension and pushed her to express complex thoughts about art, memory, and personal identity. Even when she could not immediately recall a specific term, she learned to describe her ideas using familiar synonyms and expressive gestures, discovering that meaningful communication depended on shared intention rather than an exhaustive vocabulary.

As winter approached, the town transformed under grey skies and cold coastal winds, and Elena''s daily observations took on greater depth. She realized that understanding a community involves far more than memorizing surface definitions. Beneath casual greetings lay subtle layers of irony, humor, and polite understatement that books rarely explained. One afternoon, while reviewing historical documents with an elderly researcher, she encountered a passage describing how early settlers had adapted to seasonal isolation. The text used intricate sentence structures and reflective language that required careful analysis. Rather than feeling discouraged by unfamiliar vocabulary, Elena paused to consider the author''s broader perspective. She examined how tone, context, and deliberate word choices shaped the historical narrative. In her everyday conversations, she also began noticing delicate distinctions between words that had previously seemed identical. She grasped the difference between being lonely and enjoying solitude, between passive resignation and patient resilience. This evolving awareness altered her approach to language learning. Instead of treating unknown expressions as frustrating obstacles, she welcomed ambiguity as an invitation to explore cultural nuances and cultivate sharper intuition.

When spring finally arrived, bringing vibrant flowers to the public gardens and outdoor tables to the harbor promenade, Elena recognized how profoundly her relationship with the town had matured. What had once appeared foreign and overwhelming was now woven into the fabric of her daily existence. She no longer rehearsed sentences in her head before speaking to shopkeepers, nor did she panic when someone spoke rapidly using regional expressions. Her confidence was not rooted in an illusion of flawless fluency, but in a resilient capacity to adapt, ask thoughtful questions, and embrace uncertainty with composure. Looking back at her early journal entries, she was astonished by the significant progress she had achieved through consistent, patient effort. Language was no longer an abstract collection of grammar rules to be studied in isolation; it had become a living bridge connecting her inner reflections to the vibrant community around her. As she stood on the pier watching fishing boats return against the sunset, Elena felt a profound sense of belonging, confident that every future challenge would simply be another opportunity to learn and grow.',
    TRUE,
    2,
    CURRENT_TIMESTAMP
);